#!/bin/bash

# Handy Calc
# Copyright (C) 2016, 2017 Christophe Delord
# http://cdsoft.fr/hcalc
#
# This file is part of Handy Calc.
#
# Handy Calc is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Handy Calc is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Handy Calc.  If not, see <http://www.gnu.org/licenses/>.

echo "Creating tag and archive for `echo $(stack exec hcalc version)`"

if ! stack exec hcalc version > /dev/null
then
    echo "Can not get Handy Calc current version"
    exit 1
fi

tag=$(stack exec hcalc version | sed 's/ /_/' | sed 's/ /-/' | grep '-')
arc=$(stack exec hcalc version | sed 's/ //' | sed 's/ /-/' | grep '-')

if git tag $tag
then
    mkdir -p dist
    git config tar.tgz.command "gzip -9"
    git archive --prefix=$arc/ $tag -o dist/$arc.tgz
fi
